---
abstract: 'get geocoding info for an IP address'
author:
  - 'root <root@>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Coder-HostIP
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  LWP::UserAgent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/neilbowers/Geo-Coder-HostIP
version: 0.06
